### ISSUE TITLE
アクションの存在するマスに止まった際にアクションの呼ばれるタイミングがおかしい

### ISSUE THREAD

**Issue by ry-itto** [odds0128/the_last_heisei_hackathon#21]
アクションの存在するマスに止まる
↓
アクションアラートモーダルが出てくる
↓
イベントの吹き出しが出てくる

という流れになってしまっている

**Comment by ObuchiYuki** [comment]
https://github.com/odds0128/the_last_heisei_hackathon/pull/26
にて修正しました。
